version: 2

seeds:
  - name: order_items
    config:
      column_types:
        order_item_id: integer
        order_item_order_id: integer
        order_item_product_id: integer
        order_item_quantity: integer
        order_item_subtotal: float
        order_item_product_price: float

    columns:
      - name: order_item_id
      - name: order_item_order_id
      - name: order_item_product_id
      - name: order_item_quantity
      - name: order_item_subtotal
      - name: order_item_product_price

  - name: orders
    config:
      column_types:
        order_id: integer
        order_date: timestamp
        order_customer_id: integer
        order_status: string
        
    columns:
      - name: order_id
      - name: order_date
      - name: order_customer_id
      - name: order_status

    